//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace wrMainAntiRansomeware.com.webroam.license1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="cloudsecurityBinding", Namespace="urn:cloudsecurity")]
    public partial class cloudsecurity : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Step1OperationCompleted;
        
        private System.Threading.SendOrPostCallback Step2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Step3OperationCompleted;
        
        private System.Threading.SendOrPostCallback Step4OperationCompleted;
        
        private System.Threading.SendOrPostCallback doAuthenticateOperationCompleted;
        
        private System.Threading.SendOrPostCallback logoutOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public cloudsecurity() {
            this.Url = global::wrMainAntiRansomeware.Properties.Settings.Default.wrMainAntiRansomeware_com_webroam_license1_cloudsecurity;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Step1CompletedEventHandler Step1Completed;
        
        /// <remarks/>
        public event Step2CompletedEventHandler Step2Completed;
        
        /// <remarks/>
        public event Step3CompletedEventHandler Step3Completed;
        
        /// <remarks/>
        public event Step4CompletedEventHandler Step4Completed;
        
        /// <remarks/>
        public event doAuthenticateCompletedEventHandler doAuthenticateCompleted;
        
        /// <remarks/>
        public event logoutCompletedEventHandler logoutCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:cloudsecurity#Step1", RequestNamespace="urn:cloudsecurity", ResponseNamespace="urn:cloudsecurity")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string Step1(string session, string args) {
            object[] results = this.Invoke("Step1", new object[] {
                        session,
                        args});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Step1Async(string session, string args) {
            this.Step1Async(session, args, null);
        }
        
        /// <remarks/>
        public void Step1Async(string session, string args, object userState) {
            if ((this.Step1OperationCompleted == null)) {
                this.Step1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnStep1OperationCompleted);
            }
            this.InvokeAsync("Step1", new object[] {
                        session,
                        args}, this.Step1OperationCompleted, userState);
        }
        
        private void OnStep1OperationCompleted(object arg) {
            if ((this.Step1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Step1Completed(this, new Step1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:cloudsecurity#Step2", RequestNamespace="urn:cloudsecurity", ResponseNamespace="urn:cloudsecurity")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int Step2(string session, string args) {
            object[] results = this.Invoke("Step2", new object[] {
                        session,
                        args});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Step2Async(string session, string args) {
            this.Step2Async(session, args, null);
        }
        
        /// <remarks/>
        public void Step2Async(string session, string args, object userState) {
            if ((this.Step2OperationCompleted == null)) {
                this.Step2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnStep2OperationCompleted);
            }
            this.InvokeAsync("Step2", new object[] {
                        session,
                        args}, this.Step2OperationCompleted, userState);
        }
        
        private void OnStep2OperationCompleted(object arg) {
            if ((this.Step2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Step2Completed(this, new Step2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:cloudsecurity#Step3", RequestNamespace="urn:cloudsecurity", ResponseNamespace="urn:cloudsecurity")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string Step3(string session, string args) {
            object[] results = this.Invoke("Step3", new object[] {
                        session,
                        args});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Step3Async(string session, string args) {
            this.Step3Async(session, args, null);
        }
        
        /// <remarks/>
        public void Step3Async(string session, string args, object userState) {
            if ((this.Step3OperationCompleted == null)) {
                this.Step3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnStep3OperationCompleted);
            }
            this.InvokeAsync("Step3", new object[] {
                        session,
                        args}, this.Step3OperationCompleted, userState);
        }
        
        private void OnStep3OperationCompleted(object arg) {
            if ((this.Step3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Step3Completed(this, new Step3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:cloudsecurity#Step4", RequestNamespace="urn:cloudsecurity", ResponseNamespace="urn:cloudsecurity")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string Step4(string session, string args) {
            object[] results = this.Invoke("Step4", new object[] {
                        session,
                        args});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Step4Async(string session, string args) {
            this.Step4Async(session, args, null);
        }
        
        /// <remarks/>
        public void Step4Async(string session, string args, object userState) {
            if ((this.Step4OperationCompleted == null)) {
                this.Step4OperationCompleted = new System.Threading.SendOrPostCallback(this.OnStep4OperationCompleted);
            }
            this.InvokeAsync("Step4", new object[] {
                        session,
                        args}, this.Step4OperationCompleted, userState);
        }
        
        private void OnStep4OperationCompleted(object arg) {
            if ((this.Step4Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Step4Completed(this, new Step4CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:cloudsecurity#doAuthenticate", RequestNamespace="urn:cloudsecurity", ResponseNamespace="urn:cloudsecurity")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int doAuthenticate(string session, string license) {
            object[] results = this.Invoke("doAuthenticate", new object[] {
                        session,
                        license});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void doAuthenticateAsync(string session, string license) {
            this.doAuthenticateAsync(session, license, null);
        }
        
        /// <remarks/>
        public void doAuthenticateAsync(string session, string license, object userState) {
            if ((this.doAuthenticateOperationCompleted == null)) {
                this.doAuthenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoAuthenticateOperationCompleted);
            }
            this.InvokeAsync("doAuthenticate", new object[] {
                        session,
                        license}, this.doAuthenticateOperationCompleted, userState);
        }
        
        private void OndoAuthenticateOperationCompleted(object arg) {
            if ((this.doAuthenticateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doAuthenticateCompleted(this, new doAuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:cloudsecurity#logout", RequestNamespace="urn:cloudsecurity", ResponseNamespace="urn:cloudsecurity")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int logout(string session) {
            object[] results = this.Invoke("logout", new object[] {
                        session});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void logoutAsync(string session) {
            this.logoutAsync(session, null);
        }
        
        /// <remarks/>
        public void logoutAsync(string session, object userState) {
            if ((this.logoutOperationCompleted == null)) {
                this.logoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogoutOperationCompleted);
            }
            this.InvokeAsync("logout", new object[] {
                        session}, this.logoutOperationCompleted, userState);
        }
        
        private void OnlogoutOperationCompleted(object arg) {
            if ((this.logoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logoutCompleted(this, new logoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Step1CompletedEventHandler(object sender, Step1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Step1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Step1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Step2CompletedEventHandler(object sender, Step2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Step2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Step2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Step3CompletedEventHandler(object sender, Step3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Step3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Step3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Step4CompletedEventHandler(object sender, Step4CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Step4CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Step4CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void doAuthenticateCompletedEventHandler(object sender, doAuthenticateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doAuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doAuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void logoutCompletedEventHandler(object sender, logoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class logoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal logoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591